# Generated by Django 4.0.6 on 2022-07-07 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses_app', '0002_alter_course_options_alter_course_name'),
        ('students_app', '0002_alter_student_unique_together'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='course',
        ),
        migrations.AddField(
            model_name='student',
            name='course',
            field=models.ManyToManyField(blank=True, null=True, to='courses_app.course'),
        ),
    ]
